#!/bin/zsh

# add scripts to the path
export PATH="$PATH:$(du "$HOME/.local/bin" | cut -f2 | paste -sd ':' -)"

# default programs
xdg-settings set default-web-browser brave-browser.desktop
export BROWSER='brave'
export EDITOR='nvim'
export PAGER='less'
export MANPAGER='nvim +Man!'
export READER='zathura'
export TERMINAL='st'
export TERM='st-256color'

# xdg variables
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

# zsh variables
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/zsh/zhistory"
export HISTSIZE=5000
export SAVEHIST=5000

# sound and music variables
export VST_PATH=/usr/lib/vst:/usr/local/lib/vst:~/.vst
export LXVST_PATH=/usr/lib/lxvst:/usr/local/lib/lxvst:~/.lxvst
export LADSPA_PATH=/usr/lib/ladspa:/usr/local/lib/ladspa:~/.ladspa
export LV2_PATH=/usr/lib/lv2:/usr/local/lib/lv2:~/.lv2
export DSSI_PATH=/usr/lib/dssi:/usr/local/lib/dssi:~/.dssi

# variables for home directory clean up
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export _Z_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/z/z"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export STARSHIP_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/starship/starship.toml"
export LESSHISTFILE='-'

# other variables
export SUDO_ASKPASS="$HOME/.local/bin/dmenu/dmenu_askpass"
export AWT_TOOLKIT='MToolkit wmname LG3D'
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORMTHEME='qt5ct'

# gtk theme
export GTK_THEME='Adwaita:dark'

#execute startx at startup
[ -z ${DISPLAY} ] && [ ${XDG_VTNR} -eq 1 ] && exec startx "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xinitrc"
