#!/bin/sh

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge -I"$HOME" "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# update environment variables
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# keyboard layout
setxkbmap us altgr-intl

# screen color adjustments
redshift -O 4500

# remove the mouse when idle
unclutter &

# screen lock
xss-lock ${LOCKER:-slock} &
xset s on &
xset s 450 &

# set character repeatition rate
xset r rate 300 50 &

start_dwm() {
	# compositor
	picom -f &

	# wallpaper/background
	# xwallpaper --zoom "${XDG_CONFIG_HOME:-$HOME/.config}/wallpaper"
	hsetroot -solid '#0d1010'

	# notifications
	dunst &

	# status bar
	simbar &

	# hot key daemon
	sxhkd &

	exec dwm
}

start_exwm() {
	exec emacs --exwm
}

session=${1:-dwm}

case $session in
	dwm) start_dwm;;
	exwm|emacs) start_exwm;;
esac
