[[items]]
file = "~/.config/alacritty/colors.toml"
template = "alacritty"
subtemplate = "default-256"
rewrite = true

[[items]]
file = "~/.config/dunst/dunstrc"
template = "dunst"

[[items]]
file = "~/.config/zathura/zathurarc"
template = "zathura"
