#!/bin/sh

# update
alias cupdnc='paru -Syyu --devel --noconfirm; paru -c --noconfirm; paru -Sc --noconfirm'
alias cupd='paru -Syyu --devel; paru -c; paru -Sc'

# list
alias lsd='lsd --classify --group-dirs first'
alias ls='lsd'
alias l='lsd'
alias la='lsd --almost-all'
alias ll='lsd --almost-all --long'
alias lt='lsd --tree'

# change directory
alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'
alias cd.....='cd ../../../..'

# colorize grep
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# documents view
alias img='sxiv'
alias pdf='zathura'

# ping test
alias tping='ping artixlinux.org'

# suckless
alias sucklrcp='sudo cp config.def.h config.h && sudo make clean install; sudo make clean'

# dotfiles bare git repo
alias dofi="git --git-dir=${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles/ --work-tree=$HOME"
alias dofis='dofi status'
alias dofia='dofi add'
alias doficm='dofi commit -m'
alias dofip='dofi push'

# calculator
alias calc='echo CALCULATOR && bc -q'

# calendar
alias cal='cal -m'
