import = [
	"~/.config/alacritty/colors.toml",
]

live_config_reload = true

[window]
padding = { x = 4, y = 0 }
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 10

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }
