import = [
	"~/.config/alacritty/colors/gruvbox-black.toml",
]

live_config_reload = true

[window]
padding = { x = 4, y = 0 }
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11
