format = '$username$hostname$directory$character'
right_format = "$git_branch$git_commit$git_state$git_metrics$git_status"

[cmd_duration]
disabled = true

[line_break]
disabled = true

[directory]
read_only = "\b"
style = 'bold blue'
format = '\[[($read_only\[)]($read_only_style)[$path]($style)\][($read_only\])]($read_only_style)'
repo_root_style = 'bold cyan'
repo_root_format = '\[[($read_only\[)]($read_only_style)[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)\][($read_only\])]($read_only_style)'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[\$](bold green)'

[git_metrics]
disabled = false
